import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#e5eeff",
        "primary": "#004ac6",
        "surface-dim": "#cbdbf5",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "on-primary-container": "#eeefff",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-fixed": "#131b2e",
        "surface-container-lowest": "#ffffff",
        "secondary": "#565e74",
        "surface-container-high": "#dce9ff",
        "on-surface": "#0b1c30",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed-variant": "#444749",
        "on-secondary": "#ffffff",
        "surface-tint": "#0053db",
        "on-primary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "surface-variant": "#d3e4fe",
        "tertiary": "#525657",
        "on-secondary-fixed-variant": "#3f465c",
        "secondary-fixed": "#dae2fd",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#e0e3e5",
        "surface-container-highest": "#d3e4fe",
        "inverse-surface": "#213145",
        "on-tertiary-fixed": "#191c1e",
        "surface-bright": "#f8f9ff",
        "on-error": "#ffffff",
        "on-surface-variant": "#434655",
        "outline-variant": "#c3c6d7",
        "on-secondary-container": "#5c647a",
        "on-tertiary-container": "#eff1f3",
        "on-background": "#0b1c30",
        "secondary-container": "#dae2fd",
        "tertiary-container": "#6b6e70",
        "tertiary-fixed-dim": "#c4c7c9",
        "inverse-primary": "#b4c5ff",
        "primary-container": "#2563eb",
        "background": "#f8f9ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed-dim": "#bec6e0",
        "surface": "#f8f9ff",
        "outline": "#737686"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "lg": "24px",
        "2xl": "48px",
        "xl": "32px",
        "margin-desktop": "32px",
        "3xl": "64px",
        "base": "4px",
        "md": "16px",
        "xs": "4px",
        "container-max": "1440px",
        "gutter": "24px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "display-lg": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-sm": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "display-lg-mobile": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-sm-mobile": ["Geist", "sans-serif"],
        "title-sm": ["Geist", "sans-serif"],
        "title-md": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "title-lg": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "display-md": ["Geist", "sans-serif"],
        "display-md-mobile": ["Geist", "sans-serif"],
        "headline-sm-mobile": ["Geist", "sans-serif"],
        "label-lg": ["Geist", "sans-serif"],
        "headline-md-mobile": ["Geist", "sans-serif"]
      }
    }
  },
  plugins: [],
};
export default config;
